### ISSUE TITLE
Fix `NotFound` error for views

### ISSUE THREAD

**Issue by 2br-2b** [2br-2b/StoryBot#105]
```
[ERROR   ] discord.ui.view: Ignoring exception in view <NormalTurnMessage timeout=None children=2> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Skip me' emoji=None row=None>
Traceback (most recent call last):
  File "/home/homer/.local/lib/python3.10/site-packages/discord/ui/view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "/home/homer/StoryBot-Production/cogs/views.py", line 97, in leave
    await interaction.response.send_message(f"You have been skipped in {guild_name}!")
  File "/home/homer/.local/lib/python3.10/site-packages/discord/interactions.py", line 769, in send_message
    await adapter.create_interaction_response(
  File "/home/homer/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

```
[ERROR   ] discord.ui.view: Ignoring exception in view <NormalTurnMessage timeout=None children=2> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Pause for a week' emoji=None row=None>
Traceback (most recent call last):
  File "/home/homer/.local/lib/python3.10/site-packages/discord/ui/view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "/home/homer/StoryBot-Production/cogs/views.py", line 115, in pause_for_a_week
    await interaction.response.send_message(f"Confirmed! You won't be chosen as the author for the next week in {guild_name}!\n\nIf you change your mind before then, run `/join` to unpause yourself!")
  File "/home/homer/.local/lib/python3.10/site-packages/discord/interactions.py", line 769, in send_message
    await adapter.create_interaction_response(
  File "/home/homer/.local/lib/python3.10/site-packages/discord/webhook/async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by 2br-2b** [comment]
Fixed by 59c5fd8a81522806795171526081684188ce5824
